//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblArticulo
    {
        public int codigo { get; set; }
        public string nombre { get; set; }
        public string marca { get; set; }
        public int peso { get; set; }
        public int cantidad { get; set; }
        public string descripcion { get; set; }
        public string tipoArticulo { get; set; }
        public string calificacion { get; set; }
        public string foto { get; set; }
        public string estado { get; set; }
        public decimal precioCompra { get; set; }
        public decimal precioVenta { get; set; }
        public decimal precioVentaIva { get; set; }
    }
}
