//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUsuarios
    {
        public string tipoIdentificación { get; set; }
        public string NumIdentificación { get; set; }
        public string nombreCompleto { get; set; }
        public string contrasenia { get; set; }
        public string correo { get; set; }
        public Nullable<int> telefono { get; set; }
        public string direccion { get; set; }
    }
}
